# Generated by Django 3.2.3 on 2021-06-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_number',
            field=models.IntegerField(unique=True),
        ),
    ]
