# Generated by Django 3.2.3 on 2021-06-01 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_mark_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
    ]
